api = "0.4"

[buildpack]
id = "jkutner/no-secrets"
version = "1.0.0"
name = "No Secrets"
homepage = "https://github.com/jkutner/no-secrets-buildpack"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
mixins = ["git"]

[[stacks]]
id = "io.buildpacks.samples.stacks.bionic"
mixins = ["git"]

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

